version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: twitter_web
    container_name: twitter_web
    environment:
      API_URL: http://api:8000
      VIRTUAL_HOST:
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
    ports:
      - "53000:3000"
    depends_on:
      - api
    restart: always
    networks:
      - twitter-crawler-network
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: twitter_web_api
    container_name: twitter_web_api
    environment:
      DATABASE_URL:
      MONGO_DATABASE: twitterdb
    depends_on:
      - mongo
    restart: always
    networks:
      - twitter-crawler-network
  crawler:
    build:
      context: .
      dockerfile: crawler/Dockerfile
    image: twitter_crawler
    container_name: twitter_crawler
    environment:
      TZ: "Asia/Tokyo"
      DATABASE_URL:
      MONGO_DATABASE: twitterdb
      TWITTER_CONSUMER_KEY:
      TWITTER_CONSUMER_SECRET:
      TWITTER_ACCESS_TOKEN:
      TWITTER_ACCESS_TOKEN_SECRET:
      TWITTER_USER_IDS:
      LOGGING_LEVEL:
    depends_on:
      - mongo
    restart: always
    networks:
      - twitter-crawler-network
  mongo:
    image: mongo
    container_name: twitter_crawler_mongodb
    command: --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=100
    environment:
      MONGO_DATABASE: twitterdb
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - datadir:/data/db
      - mongo-log:/var/log/mongodb
    ports:
      - "27019:27017"
    restart: always
    networks:
      - twitter-crawler-network
volumes:
  datadir:
  mongo-log:

networks:
#  proxy-network:
#    external: true
#    name: proxy_network
  twitter-crawler-network:
    name: twitter_crawler_network